services:
  medleaft:
    build: .
    container_name: medleaft_app
    ports:
      - "8501:8501"
    volumes:
      - ./Rag/database/Vectordb:/app/Rag/database/Vectordb
      - ./Rag/database/files:/app/Rag/database/files
